### ISSUE TITLE
Usage in nextjs app withouth mdx deck

### ISSUE THREAD

**Issue by hardvain** [pomber/code-surfer#90]
Hello, Is it possible to use this in a nextjs app preferably without the dependency of mdx-deck? I am fine with adding mdx deck as well but I was not able to get it work with nextjs app

**Comment by pomber** [comment]
You could try to use the @code-surfer/standalone package, but it isn't documented. There are some usage examples here: https://github.com/pomber/code-surfer/tree/master/sites/book/src

(for something more ambitious wait for https://github.com/code-hike/codehike)

**Comment by JakubKoralewski** [comment]
I'm getting this error after adding `@code-surfer/standalone` as a dev dependency :confused::

```bash
error - ./node_modules/@code-surfer/themes/dist/themes.esm.js
Module not found: Can't resolve 'theme-ui' in '.\node_modules\@code-surfer\themes\dist'
ModuleNotFoundError: Module not found: Error: Can't resolve 'theme-ui' in '.\node_modules\@code-surfer\themes\dist'
    at .\node_modules\webpack\lib\Compilation.js:925:10
    at .\node_modules\webpack\lib\NormalModuleFactory.js:401:22
    at .\node_modules\webpack\lib\NormalModuleFactory.js:130:21
    at .\node_modules\webpack\lib\NormalModuleFactory.js:224:22
    at .\node_modules\neo-async\async.js:2830:7
    at .\node_modules\neo-async\async.js:6877:13
    at .\node_modules\webpack\lib\NormalModuleFactory.js:214:25
    at .\node_modules\enhanced-resolve\lib\Resolver.js:213:14
    at .\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (.\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at .\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7
    at .\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (.\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at .\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (.\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:25:1)
    at .\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43
```
